apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: main-policy
  namespace: acm-policies
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values: 
          - main-policy
---
apiVersion: v1
kind: Namespace
metadata:
  name: ggithubcom-mmwillingham-acm-acs-ns
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  annotations:
    apps.open-cluster-management.io/reconcile-rate: medium
  name: ggithubcom-mmwillingham-acm-acs
  namespace: ggithubcom-mmwillingham-acm-acs-ns
spec:
  type: Git
  pathname: 'https://github.com/mmwillingham/acm-acs.git'
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: crc
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: main-policy
  name: main-policy-subscription-1
  namespace: acm-policies
spec:
  channel: ggithubcom-mmwillingham-acm-acs-ns/ggithubcom-mmwillingham-acm-acs
  placement:
    placementRef:
      kind: Placement
      name: main-policy-placement-1
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  labels:
    app: main-policy
  name: main-policy-placement-1
  namespace: acm-policies
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
  clusterSets:
