apiVersion: v1
kind: Namespace
metadata:
  name: acm-policies
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: main-policy
spec:
  componentKinds:
    - group: apps.open-cluster-management.io
      kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app  
        operator: In
        values:
          - main-policy
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  annotations:
    apps.open-cluster-management.io/reconcile-rate: medium
  name: main-policy
spec:
  type: Git
  pathname: "https://github.com/mmwillingham/acm-acs.git"
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: crc
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: main-policy
  name: main-policy-subscription
spec:
  allow:
    - apiVersion: policy.open-cluster-management.io/v1
      kinds:
        - "*"
    - apiVersion: apps.open-cluster-management.io/v1
      kinds:
        - PlacementRule
  channel: main-policy/main-policy
  placement:
    placementRef:
      kind: PlacementRule
      name: main-policy-placement
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: main-policy
  name: main-policy-placement
spec:
  clusterSelector:
    matchLabels:
      "local-cluster": "true"
