apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: bolauder
  namespace: acm-policies
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values: 
          - bolauder
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: crc
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: bolauder
  name: bolauder-subscription-1
  namespace: acm-policies
spec:
  channel: ggithubcom-mmwillingham-acm-acs-ns/ggithubcom-mmwillingham-acm-acs
  placement:
    placementRef:
      kind: Placement
      name: bolauder-placement-1
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  labels:
    app: bolauder
  name: bolauder-placement-1
  namespace: acm-policies
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
  clusterSets:
    - hub
