apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: main-policy
  namespace: acm-policies
  annotations:
    apps.open-cluster-management.io/deployables: ''
    apps.open-cluster-management.io/subscriptions: acm-policies/main-policy-subscription-1,acm-policies/main-policy-subscription-1-local
spec:
  componentKinds:
    - group: apps.open-cluster-management.io
      kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - main-policy
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: main-policy-subscription-1
  namespace: acm-policies
  annotations:
    apps.open-cluster-management.io/cluster-admin: 'true'
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: crc
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: main-policy
    app.kubernetes.io/part-of: main-policy
    apps.open-cluster-management.io/reconcile-rate: medium
spec:
  channel: acm-policies/main-policy
  placement:
    placementRef:
      name: main-policy-placement
      kind: PlacementRule
posthooks: {}
prehooks: {}
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: main-policy-placement
  namespace: acm-policies
  annotations:
  labels:
    app: main-policy
spec:
  clusterSelector:
    matchLabels:
      local-cluster: 'true'
